Add PBR shader tutorial guide
Sigmmma/c20 pull request #175
Opened 2022-05-25 03:56 UTC by TheChunkierBean

A written guide that showcases how to port a PBR texture set to Halo 3.

2022-05-25 20:00 UTC, num0005 requested changes
Please setup a page.yml see https://github.com/Sigmmma/c20/blob/master/src/content/h2/guides/map-making/level-creation/page.yml for an example

2022-05-25 20:18 UTC, num0005 requested changes
you can also remove this since the page.yml handles this already.

2022-05-25 20:18 UTC, num0005 commented
I will review the content later but that should be all the technical issues.

2022-05-25 20:29 UTC, TheChunkierBean commented
Removed acknowledgements from readme.md

2022-05-27 10:39 UTC, num0005 approved these changes
Looks fine apart from the few things pointed out.

2022-05-27 10:39 UTC, num0005 commented on src/content/h3/guides/shaders/pbr-shader/readme.md
> +
Please use the `.alert` syntax for this (see other pages for an example of how to do it.

2022-05-27 10:39 UTC, num0005 commented on src/content/h3/guides/shaders/pbr-shader/page.yml
> +  en: H3 pbr shader guide
capitalize PBR
```suggestion
  en: H3 PBR shader guide
```

2022-05-27 10:39 UTC, num0005 commented on src/content/h3/guides/shaders/pbr-shader/readme.md
> +Physically based rendering (PBR) is a way of rendering images that mimics how light works in the real world. Most modern game engines have a form of this method in there shading systems.
Maybe add a wikipedia link here?

2022-05-27 10:39 UTC, num0005 commented on src/content/h3/guides/shaders/pbr-shader/readme.md
> +**NOTE**: *If you have a texture set that does not include a **Metallic map**, you do not need to make a Specular map. You can skip this step.*
ditto

2022-05-27 10:39 UTC, num0005 commented on src/content/h3/guides/shaders/pbr-shader/readme.md
> +Make sure to identify what type of Normal map you have. Halo 3 uses DirectX normals and those do not need to be converted to work with the engine. Simply save the normal as a .TIF in your asset's bit
maybe link to something that explains what the difference between those two is? Or would it be obvious to anyone reading this guide?

2022-05-27 22:00 UTC, num0005 approved these changes

2022-05-27 22:00 UTC, merged